[build]
  publish = "."

[[redirects]]
  from = "/loja"
  to   = "/loja.html"
  status = 200

[[redirects]]
  from = "/admin"
  to   = "/admin.html"
  status = 200

[[redirects]]
  from = "/login"
  to   = "/login.html"
  status = 200

[[redirects]]
  from = "/cadastro"
  to   = "/cadastro.html"
  status = 200

[[redirects]]
  from = "/carrinho"
  to   = "/carrinho.html"
  status = 200

[[redirects]]
  from = "/conta"
  to   = "/conta.html"
  status = 200
